Repository TomIA24/unow-front, pull requests merged in 2024-09, with the labels that each got.

#7 make the collab not disappear in small devices
  src/component/Home/Categories/index.jsx
  src/component/Home/Collab/styles.module.css
  src/component/Main/styles.module.css
Labels: enhancement

#8 Fix/route name
  src/component/Home/Categories/styles.module.css
  src/component/Personalize/index.jsx
  src/component/Quiz/Questions/styles.module.css
Labels: bug

#9 fix the design in the courses and training page
  .env
  public/svg/polygon.svg
  src/App.js
  src/component/GenericSwitcher/index.jsx
  src/component/GenericSwitcher/styles.module.css
  src/component/Home/Categories/CategoryDetails/index.jsx
  src/component/Home/Categories/CategoryDetails/styles.modules.css
  src/component/Home/Categories/index.jsx
  src/component/TopBar/index.jsx
  src/component/TopBar/styles.module.css
  src/core/constants/breakpoints.js
  src/hooks/useScreenSize.jsx
Labels: bug, enhancement

#16 Feat/request axios interceptor config
  .env
  src/component/Home/Categories/index.jsx
  src/core/api/ErrorHandler.js
  src/core/api/SuccessHandler.js
  src/core/api/codeMessage.js
  src/core/api/request.js
Labels: enhancement

#10 fixed/nav
  src/component/Main/index.jsx
  src/component/Nav/index.jsx
  src/component/Personalize/index.jsx
  src/component/Quiz/index.jsx
  src/component/Quiz/nabar/index.jsx
  src/component/Quiz/nabar/styles.module.css
  src/component/Quiz/styles.module.css
  src/component/SignUp/index.jsx
Labels: bug

#11 Routing/quiz course
  .gitignore
  src/App.js
  src/component/Course/index.jsx
  src/component/Course/paid/index.jsx
  src/component/Home/Footer/index.jsx
  src/component/Nav/index.jsx
  src/component/Nav/styles.module.css
  src/component/Quiz/Questions/index.jsx
  src/component/Quiz/nabar/index.jsx
  src/component/Quiz/nabar/styles.module.css
Labels: bug

#18 .Fix/err handle success handler
  package-lock.json
  package.json
  src/App.js
  src/component/Home/Categories/index.jsx
  src/core/api/ErrorHandler.js
  src/core/api/SuccessHandler.js
  src/core/api/errorHandler.js
  src/core/api/request.js
  src/core/api/successHandler.js
Labels: bug

#19 Ref/training and course card
  src/component/CourseTrainingCard/index.jsx
  src/component/CourseTrainingCard/styles.module.css
  src/component/Home/Categories/CategoryDetails/CourseItem/index.jsx
  src/component/Home/Categories/CategoryDetails/CourseItem/styles.module.css
  src/component/Home/Categories/CategoryDetails/hooks/useFetchData.js
  src/component/Home/Categories/CategoryDetails/index.jsx
  src/component/Home/Categories/CategoryDetails/styles.modules.css
  src/component/Main/index.jsx
  src/component/ResourceCard/index.jsx
  src/component/ResourceCard/styles.module.css
  src/component/SearchBar/Index.jsx
  src/component/SearchBar/styles.module.css
  src/component/assets/loupe.svg
  src/hooks/useDebouncedState.jsx
Labels: enhancement

#24 Fix/styling issues
  .env
  public/svg/categories/business.svg
  public/svg/categories/computer_science.svg
  public/svg/categories/information_technology.svg
  public/svg/categories/language_learning.svg
  public/svg/categories/personal_development.svg
  src/component/CourseTrainingCard/styles.module.css
  src/component/GenericSwitcher/index.jsx
  src/component/Home/AboutUs/index.jsx
  src/component/Home/Categories/CategoryDetails/index.jsx
  src/component/Home/Categories/CategoryDetails/styles.modules.css
  src/component/Home/Categories/index.jsx
  src/component/Home/Categories/styles.module.css
  src/component/Home/Featured Trainers/index.jsx
  src/component/Home/Footer/index.jsx
  src/component/Home/HomeInterface.jsx
  src/component/Home/chatbot/chatbot.jsx
  src/component/Home/styles.module.css
  src/component/Main/index.jsx
  src/component/Nav/index.jsx
  src/component/SearchBar/styles.module.css
  src/component/footer/index.jsx
  src/index.css
  src/index.js
Labels: bug, enhancement

#22 Feat/spotlight home page
  src/component/Main/index.jsx
  src/component/Spotlight/index.jsx
  src/component/Spotlight/styles.module.css
  src/hooks/useClickOutside.jsx
Labels: enhancement

#26 Fix/background color bug
  .env
  src/component/Main/index.jsx
Labels: bug
