Repository TomIA24/unow-front, pull requests merged in 2024-10, with the labels that each got.

#29 Feat/trainer profile
  src/App.js
  src/component/Login/index.jsx
  src/component/ProfileTrainer/EditProfile/index.jsx
  src/component/ProfileTrainer/EditProfile/styles.module.css
  src/component/ProfileTrainer/EditProfile/useForm.js
  src/component/ProfileTrainer/InfoUser/ProgramsModal.jsx
  src/component/ProfileTrainer/InfoUser/index.jsx
  src/component/ProfileTrainer/InfoUser/styles.module.css
  src/component/ProfileTrainer/InfoUser/useProgramsModal.js
  src/component/ProfileTrainer/components/MobileDeiveTopBar/index.jsx
  src/component/ProfileTrainer/components/MobileDeiveTopBar/styles.module.css
  src/component/ProfileTrainer/components/SideBarButton/index.jsx
  src/component/ProfileTrainer/components/SideBarButton/styles.module.css
  src/component/ProfileTrainer/components/TopBarInfo/index.jsx
  src/component/ProfileTrainer/components/TopBarInfo/styles.module.css
  src/component/ProfileTrainer/index.jsx
  src/component/ProfileTrainer/styles.module.css
  src/component/assets/arrow.svg
  src/component/slider/index.jsx
  src/core/api/request.js
  src/index.css
  src/shared/components/Inputs/Input.jsx
  src/shared/components/Inputs/MultiSelect.jsx
  src/shared/components/Inputs/Select.jsx
  src/shared/components/Inputs/styles.module.css
Labels: enhancement

#32 Feat/calendar
  src/component/ProfileTrainer/Calendar/createServiceWorker.js
  src/component/ProfileTrainer/Calendar/demo-data/tasks.js
  src/component/ProfileTrainer/Calendar/demo.jsx
  src/component/ProfileTrainer/Calendar/index.jsx
  src/component/ProfileTrainer/Calendar/styles.css
  src/component/ProfileTrainer/Calendar/styles.module.css
  src/component/ProfileTrainer/Calendar/useCalendar.js
  src/component/ProfileTrainer/components/OnNavigate/index.jsx
  src/component/ProfileTrainer/components/OnNavigate/styles.module.css
  src/component/ProfileTrainer/index.jsx
  src/component/ProfileTrainer/styles.module.css
  src/shared/calendarUtils.js
Labels: enhancement

#31 Feat/actu mongdats
  .env
  package-lock.json
  src/component/ProfileTrainer/Actu/ActionButtons.jsx
  src/component/ProfileTrainer/Actu/index.jsx
  src/component/ProfileTrainer/Actu/styles.css
  src/component/ProfileTrainer/Actu/styles.module.css
  src/component/ProfileTrainer/Actu/useNotifTrainer.js
  src/component/ProfileTrainer/index.jsx
Labels: bug, enhancement

#41 Feat/trainer trainings courses
  .env
  src/App.js
  src/component/AddRessources/index.jsx
  src/component/AddRessources/styles.module.css
  src/component/ImgUploadSection/index.jsx
  src/component/ImgUploadSection/styles.module.css
  src/component/Loading/index.jsx
  src/component/Loading/styles.css
  src/component/ProfileTrainer/Actu/styles.css
  src/component/ProfileTrainer/Courses/CourseForm/index.jsx
  src/component/ProfileTrainer/Courses/CourseForm/styles.module.css
  src/component/ProfileTrainer/Courses/CourseForm/useCourseForm.js
  src/component/ProfileTrainer/Courses/index.jsx
  src/component/ProfileTrainer/Courses/styles.module.css
  src/component/ProfileTrainer/Courses/useCourses.js
  src/component/ProfileTrainer/Trainings/index.jsx
  src/component/ProfileTrainer/Trainings/styles.module.css
  src/component/ProfileTrainer/index.jsx
  src/component/ProfileTrainer/rooms/index.jsx
  src/component/ProfileTrainer/rooms/styles.module.css
  src/component/ProfileTrainer/styles.module.css
  src/component/VideosSelector/index.jsx
  src/component/VideosSelector/styles.module.css
  src/core/api/request.js
  src/index.css
Labels: enhancement

#43 Feat/make program related to category
  src/component/ProfileTrainer/InfoUser/ProgramsModal.jsx
  src/component/ProfileTrainer/InfoUser/index.jsx
  src/component/ProfileTrainer/InfoUser/useProgramsModal.js
  src/component/ProfileTrainer/index.jsx
  src/shared/components/Inputs/Select.jsx
Labels: enhancement

#47 Feat/trainer unavailability
  .env
  src/component/ProfileTrainer/Actu/useNotifTrainer.js
  src/component/ProfileTrainer/Calendar/index.jsx
  src/component/ProfileTrainer/Calendar/useCalendar.js
  src/component/ProfileTrainer/Trainings/index.jsx
  src/component/ProfileTrainer/Trainings/useTrainings.js
  src/component/ProfileTrainer/components/DayDetailsModal/TrainerConfirmation.jsx
  src/component/ProfileTrainer/components/DayDetailsModal/Unavailability.jsx
  src/component/ProfileTrainer/components/DayDetailsModal/hooks/useTrainerConfirmation.js
  src/component/ProfileTrainer/components/DayDetailsModal/hooks/useUnavailability.js
  src/component/ProfileTrainer/components/DayDetailsModal/index.jsx
  src/component/ProfileTrainer/components/DayDetailsModal/styles.module.css
  src/core/api/errorHandler.js
  src/core/api/successHandler.js
  src/shared/calendarUtils.js
  src/shared/components/Inputs/Input.jsx
  src/shared/components/button/index.jsx
  src/shared/components/button/styles.module.css
Labels: enhancement

#53 Add/select currency
  .env
  src/component/ProfileTrainer/Actu/styles.module.css
  src/component/ProfileTrainer/Actu/useNotifTrainer.js
  src/component/ProfileTrainer/Calendar/index.jsx
  src/component/ProfileTrainer/Calendar/styles.css
  src/component/ProfileTrainer/Courses/styles.module.css
  src/component/ProfileTrainer/InfoUser/styles.module.css
  src/component/ProfileTrainer/Trainings/styles.module.css
  src/component/ProfileTrainer/components/DayDetailsModal/Unavailability.jsx
  src/component/ProfileTrainer/components/MobileDeiveTopBar/index.jsx
  src/component/ProfileTrainer/components/SideBarButton/styles.module.css
  src/component/ProfileTrainer/styles.module.css
  src/shared/calendarUtils.js
  src/shared/components/Inputs/Select.jsx
Labels: enhancement

#57 Dev catalog
  package-lock.json
  package.json
  src/App.js
  src/component/Catalog/index.jsx
  src/component/Catalog/styles.module.css
  src/component/Contact/index.jsx
  src/setupProxy.js
Labels: enhancement

#60 Ref/cart condidate
  .env
  src/component/Course/standard/index.jsx
  src/component/GenericSwitcher/index.jsx
  src/component/GenericSwitcher/styles.module.css
  src/component/Home/Categories/CategoryDetails/index.jsx
  src/component/Login/index.jsx
  src/component/ProfileClient/Profile/index.jsx
  src/component/ProfileClient/cart/index.jsx
  src/component/ProfileClient/cart/styles.module.css
  src/component/ProfileClient/components/CartCard/index.jsx
  src/component/ProfileClient/components/CartCard/styles.module.css
  src/component/ProfileClient/components/ConfirmPaidModal/index.jsx
  src/component/ProfileClient/components/ConfirmPaidModal/styles.module.css
  src/component/ProfileClient/hooks/use-cart.js
  src/component/ProfileClient/hooks/use-confirm-paid.js
  src/component/Training/standard/index.jsx
  src/component/assets/icon_course.png
  src/component/assets/icon_course.svg
  src/component/assets/icon_training.png
  src/component/assets/icon_training.svg
  src/component/assets/icon_voucher.svg
  src/shared/components/button/index.jsx
  src/shared/components/button/styles.module.css
Labels: bug, enhancement

#64 Fix/cart issues
  package-lock.json
  src/component/Course/standard/index.jsx
  src/component/ProfileClient/cart/index.jsx
  src/component/ProfileClient/components/CartCard/index.jsx
  src/component/ProfileClient/components/ConfirmPaidModal/index.jsx
  src/component/ProfileClient/components/CourseCardElement/index.jsx
  src/component/ProfileClient/hooks/use-cart.js
  src/component/ProfileClient/hooks/use-confirm-paid.js
  src/component/Training/index.jsx
  src/component/Training/standard/index.jsx
Labels: bug

#68 fix the bug appears in Agile training cart
  .env
  src/component/Training/standard/index.jsx
Labels: bug
